spring:
  application:
    name: wire-me-up-code-test
  datasource:
    url: jdbc:h2:mem:codetest;DB_CLOSE_DELAY=-1
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    com.codetest: DEBUG
